	#base	"../../../_stream/resource/ui/disguise_menu/hudmenuspydisguise.res"
	#base	"../../../_lionhud/resource/ui/disguise_menu/hudmenuspydisguise.res"
	#base	"../../../_jofrehud/resource/ui/disguise_menu/hudmenuspydisguise.res"
	#base	"../../../_jofrehud/_tf2fix/resource/ui/disguise_menu/hudmenuspydisguise.res"
//	#base	"../../../_tf2hud/resource/ui/disguise_menu/hudmenuspydisguise.res"