	#base	"../../_stream/resource/ui/freezepanelkillerhealth.res"
	#base	"../../_lionhud/resource/ui/freezepanelkillerhealth.res"
	#base	"../../_jofrehud/resource/ui/freezepanelkillerhealth.res"
	#base	"../../_jofrehud/_tf2fix/resource/ui/freezepanelkillerhealth.res"	
//	#base	"../../_tf2hud/resource/ui/freezepanelkillerhealth.res"