	#base	"../../_stream/resource/ui/hudtournament.res"
	#base	"../../#users/dane/resource/ui/hudtournament.res"
	#base	"../../_lionhud/resource/ui/hudtournament.res"
	#base	"../../_jofrehud/resource/ui/hudtournament.res"
	#base	"../../_tf2hud/resource/ui/hudtournament.res"